name: CI
on: [push]

jobs:
  spec:
    name: Spec
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Install RabbitMQ
        run: sudo apt-get update && sudo apt-get install -y rabbitmq-server

      - name: Verify RabbitMQ started correctly
        run: while true; do sudo rabbitmq-diagnostics status 2>/dev/null && break; echo -n .; sleep 2; done

      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Install shards
        run: shards install

      - name: Run tests
        run: crystal spec --no-color --order random

  tls:
    name: Spec (TLS)
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Install RabbitMQ
        run: sudo apt-get update && sudo apt-get install -y rabbitmq-server

      - name: Stop RabbitMQ
        run: sudo systemctl stop rabbitmq-server

      - name: Install github.com/FiloSottile/mkcert
        run: brew install mkcert

      - name: Create local CA
        run: sudo CAROOT=/etc/rabbitmq $(brew --prefix)/bin/mkcert -install

      - name: Create certificate
        run: |
          sudo $(brew --prefix)/bin/mkcert -key-file /etc/rabbitmq/localhost-key.pem -cert-file /etc/rabbitmq/localhost.pem localhost
          sudo chmod +r /etc/rabbitmq/localhost-key.pem

      - name: Create RabbitMQ config
        run: |
          sudo tee /etc/rabbitmq/rabbitmq.conf <<'EOF'
          listeners.ssl.default  = 5671
          ssl_options.cacertfile = /etc/rabbitmq/rootCA.pem
          ssl_options.certfile   = /etc/rabbitmq/localhost.pem
          ssl_options.keyfile    = /etc/rabbitmq/localhost-key.pem
          EOF
      - name: Start RabbitMQ
        run: sudo systemctl start rabbitmq-server

      - name: Verify RabbitMQ started correctly
        run: while true; do sudo rabbitmq-diagnostics status 2>/dev/null && break; echo -n .; sleep 2; done

      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Install shards
        run: shards install

      - name: Run tests
        run: crystal spec --no-color --order random
        env:
          UPSTREAM_TLS: true
